//
// main.cpp
// Main file
// ----------------------------------
// Developed with embedXcode+
// https://embedXcode.weebly.com
//
// Project 		Master_Weather_Station
//
// Created by 	freddie, 2/9/19 3:31 PM
//              Kingston Co.
//
// Copyright 	© freddie, 2019
// Licence 		All rights reserved
//
// See 			Master_Weather_Station.ino and ReadMe.txt for references
//
// ----------------------------------
// DO NOT EDIT THIS FILE.
// THE SKETCH IS IN Master_Weather_Station.ino
// ----------------------------------
//
// Last update: Jun 30, 2017 release 7.5.0

// IDE selection
#if defined(EMBEDXCODE)

// Core library and main()
// Minimal proxy main() to be updated at build
#include "Arduino.h"

int main(void)
{
    setup();

    for (;;)
    {
        loop();
    }

    return 0;
}

// Sketch
#include "Master_Weather_Station.ino"


#endif                                                                          // end embedXcode

